spring:
  application:
    name: pedidos-api

  datasource:
    url: jdbc:postgresql://localhost:5433/pedidos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      pool-name: pedidos-db
      max-lifetime: 600000
      connection-timeout: 100000
      connection-test-query: select 1

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true